<?php

namespace CdmFr\Model\V1_1_1\CdmFr\CDM;

/**
 * Class representing PropertiesAType
 */
class PropertiesAType
{

    /**
     * @property string $language
     */
    private $language = null;

    /**
     * This is the source address/identifier of the
     *  Enterprise system that is initiating the data
     *  transfer.
     *
     * @property string $datasource
     */
    private $datasource = null;

    /**
     * An identifier for the target Enterprise
     *  System. This identifier should be capable of uniquely
     *  identifying the appropriate Enterprise
     *  System.
     *
     * @property string[] $target
     */
    private $target = null;

    /**
     * Describes the type of event that caused the
     *  source system to generate the data objects.
     *
     * @property string $type
     */
    private $type = null;

    /**
     * The date and time the data objects were
     *  generated by the data source.
     *
     * @property \CdmFr\Model\V1_1_1\CdmFr\CDMdateTimeType $datetime
     */
    private $datetime = null;

    /**
     * @property \CdmFr\Model\V1_1_1\CdmFr\InfoBlock $infoBlock
     */
    private $infoBlock = null;

    /**
     * Gets as language
     *
     * @return string
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Sets a new language
     *
     * @param string $language
     * @return self
     */
    public function setLanguage($language)
    {
        $this->language = $language;
        return $this;
    }

    /**
     * Gets as datasource
     *
     * This is the source address/identifier of the
     *  Enterprise system that is initiating the data
     *  transfer.
     *
     * @return string
     */
    public function getDatasource()
    {
        return $this->datasource;
    }

    /**
     * Sets a new datasource
     *
     * This is the source address/identifier of the
     *  Enterprise system that is initiating the data
     *  transfer.
     *
     * @param string $datasource
     * @return self
     */
    public function setDatasource($datasource)
    {
        $this->datasource = $datasource;
        return $this;
    }

    /**
     * Adds as target
     *
     * An identifier for the target Enterprise
     *  System. This identifier should be capable of uniquely
     *  identifying the appropriate Enterprise
     *  System.
     *
     * @return self
     * @param string $target
     */
    public function addToTarget($target)
    {
        $this->target[] = $target;
        return $this;
    }

    /**
     * isset target
     *
     * An identifier for the target Enterprise
     *  System. This identifier should be capable of uniquely
     *  identifying the appropriate Enterprise
     *  System.
     *
     * @param scalar $index
     * @return boolean
     */
    public function issetTarget($index)
    {
        return isset($this->target[$index]);
    }

    /**
     * unset target
     *
     * An identifier for the target Enterprise
     *  System. This identifier should be capable of uniquely
     *  identifying the appropriate Enterprise
     *  System.
     *
     * @param scalar $index
     * @return void
     */
    public function unsetTarget($index)
    {
        unset($this->target[$index]);
    }

    /**
     * Gets as target
     *
     * An identifier for the target Enterprise
     *  System. This identifier should be capable of uniquely
     *  identifying the appropriate Enterprise
     *  System.
     *
     * @return string[]
     */
    public function getTarget()
    {
        return $this->target;
    }

    /**
     * Sets a new target
     *
     * An identifier for the target Enterprise
     *  System. This identifier should be capable of uniquely
     *  identifying the appropriate Enterprise
     *  System.
     *
     * @param string[] $target
     * @return self
     */
    public function setTarget(array $target)
    {
        $this->target = $target;
        return $this;
    }

    /**
     * Gets as type
     *
     * Describes the type of event that caused the
     *  source system to generate the data objects.
     *
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Sets a new type
     *
     * Describes the type of event that caused the
     *  source system to generate the data objects.
     *
     * @param string $type
     * @return self
     */
    public function setType($type)
    {
        $this->type = $type;
        return $this;
    }

    /**
     * Gets as datetime
     *
     * The date and time the data objects were
     *  generated by the data source.
     *
     * @return \CdmFr\Model\V1_1_1\CdmFr\CDMdateTimeType
     */
    public function getDatetime()
    {
        return $this->datetime;
    }

    /**
     * Sets a new datetime
     *
     * The date and time the data objects were
     *  generated by the data source.
     *
     * @param \CdmFr\Model\V1_1_1\CdmFr\CDMdateTimeType $datetime
     * @return self
     */
    public function setDatetime(\CdmFr\Model\V1_1_1\CdmFr\CDMdateTimeType $datetime)
    {
        $this->datetime = $datetime;
        return $this;
    }

    /**
     * Gets as infoBlock
     *
     * @return \CdmFr\Model\V1_1_1\CdmFr\InfoBlock
     */
    public function getInfoBlock()
    {
        return $this->infoBlock;
    }

    /**
     * Sets a new infoBlock
     *
     * @param \CdmFr\Model\V1_1_1\CdmFr\InfoBlock $infoBlock
     * @return self
     */
    public function setInfoBlock(\CdmFr\Model\V1_1_1\CdmFr\InfoBlock $infoBlock)
    {
        $this->infoBlock = $infoBlock;
        return $this;
    }


}

