CdmFr\Model\V1_1_1\Xhtml\Meta:
    xml_root_name: meta
    xml_root_namespace: 'http://www.w3.org/1999/xhtml'
    properties:
        lang:
            expose: true
            access_type: public_method
            serialized_name: lang
            accessor:
                getter: getLang
                setter: setLang
            xml_attribute: true
            type: string
        dir:
            expose: true
            access_type: public_method
            serialized_name: dir
            accessor:
                getter: getDir
                setter: setDir
            xml_attribute: true
            type: string
        id:
            expose: true
            access_type: public_method
            serialized_name: id
            accessor:
                getter: getId
                setter: setId
            xml_attribute: true
            type: string
        httpEquiv:
            expose: true
            access_type: public_method
            serialized_name: http-equiv
            accessor:
                getter: getHttpEquiv
                setter: setHttpEquiv
            xml_attribute: true
            type: \AnyType
        name:
            expose: true
            access_type: public_method
            serialized_name: name
            accessor:
                getter: getName
                setter: setName
            xml_attribute: true
            type: \AnyType
        content:
            expose: true
            access_type: public_method
            serialized_name: content
            accessor:
                getter: getContent
                setter: setContent
            xml_attribute: true
            type: \AnyType
        scheme:
            expose: true
            access_type: public_method
            serialized_name: scheme
            accessor:
                getter: getScheme
                setter: setScheme
            xml_attribute: true
            type: \AnyType
