CdmFr\Model\V1_1_1\Xhtml\Param:
    xml_root_name: param
    xml_root_namespace: 'http://www.w3.org/1999/xhtml'
    properties:
        id:
            expose: true
            access_type: public_method
            serialized_name: id
            accessor:
                getter: getId
                setter: setId
            xml_attribute: true
            type: string
        name:
            expose: true
            access_type: public_method
            serialized_name: name
            accessor:
                getter: getName
                setter: setName
            xml_attribute: true
            type: \AnyType
        value:
            expose: true
            access_type: public_method
            serialized_name: value
            accessor:
                getter: getValue
                setter: setValue
            xml_attribute: true
            type: \AnyType
        valuetype:
            expose: true
            access_type: public_method
            serialized_name: valuetype
            accessor:
                getter: getValuetype
                setter: setValuetype
            xml_attribute: true
            type: string
        type:
            expose: true
            access_type: public_method
            serialized_name: type
            accessor:
                getter: getType
                setter: setType
            xml_attribute: true
            type: string
